[package]
name = "formalmusicd"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
formalmusic-api = { workspace = true, features = ["io"] }
formalmusic-innertube.workspace = true
formalmusic-player.workspace = true
formalmusic-extras.workspace = true
anyhow.workspace = true
dirs.workspace = true
fastrand = "2"
parking_lot.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
libc = "0.2"
rusqlite = { version = "0.40", features = ["bundled"] }

[target.'cfg(target_os = "linux")'.dependencies]
mpris-server = "0.9"

[dev-dependencies]
tempfile = "3"
