[package]
name = "formalmusic-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
kopuz-api.workspace = true
kopuz-client.workspace = true
kopuz-config.workspace = true
formalmusic-extras.workspace = true
tokio.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_json.workspace = true
tracing.workspace = true
parking_lot.workspace = true
dirs.workspace = true
thiserror.workspace = true
async-trait = "0.1"
futures-util = "0.3"
libc = "0.2"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }

[target.'cfg(windows)'.dependencies]
kopuz-proto.workspace = true
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Threading"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
